### ISSUE TITLE
你好，我们想把Assigning Personality应用到我们的“AI男友”项目，请问提供技术支持吗？

### ISSUE THREAD

**Issue by 1973sir** [ghosthamlet/persona#1]
你好，我们想把Assigning Personality应用到我们的“AI男友”项目，请问提供技术支持吗？可以付费。
方便的话可以加我微信详聊：
![微信图片_20201112113635](https://user-images.githubusercontent.com/1441981/111276128-f41e8780-8671-11eb-89df-d6a096a400f1.jpg)
谢谢！

**Comment by ghosthamlet** [comment]
@1973sir 不好意思，我刚看到这个留言。谢谢关注。不过不好意思，我最近在研究新的算法，所以可能时间和精力都会不够。

**Comment by 1973sir** [comment]
> @1973sir 不好意思，我刚看到这个留言。谢谢关注。不过不好意思，我最近在研究新的算法，所以可能时间和精力都会不够。

好的，没关系，谢谢！
